### ISSUE TITLE
The interpreter should be direnv, not the shell

### ISSUE THREAD

**Issue by mattalxndr** [cab404/vscode-direnv#7]
There are lines like [`layout`](https://github.com/direnv/direnv/wiki/Python#venv-stdlib-module) that are not meant to be executed by the shell.

```shell
% cd /path/.envrc
layout pipenv
export FOO=bar
```

This is the error I get when I press "Allow" on the notification:

```shell
[Running] bash "/path/.envrc"
/path/.envrc: line 1: layout: command not found

[Done] exited with code=127 in 0.021 seconds
```

Great extension, by the way. Fills a need. 

Maybe I'll find some free time to PR.

**Comment by cab404** [comment]
What version of vscode-direnv do you use?

**Comment by cab404** [comment]
@mattalexx Please, clarify the issue.

**Comment by mattalxndr** [comment]
Sorry, didn't circle back to this in a reasonable time. I'll come back if it comes up again.
